name: Docker Publish

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to use'
        required: true
        type: string
        default: 'latest'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: yeonhyukkim/fake-push-server
  DOCKER_USERNAME: yeonhyukkim


jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || steps.get-tag.outputs.tag }}
    steps:
      - name: Get tag
        if: github.event_name != 'workflow_dispatch'
        id: get-tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: get-tag
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        platform: [
          { os: ubuntu-24.04, arch: linux/amd64, tag-postfix: amd },
          { os: ubuntu-24.04-arm, arch: linux/arm64, tag-postfix: arm }
        ]
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Image with Spring boot Graalvm Support
        run: ./gradlew bootBuildImage --imageName=${{ env.IMAGE_NAME }}:${{ needs.get-tag.outputs.tag }} --imagePlatform=${{ matrix.platform.arch }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # run docker push command without using docker/build-push-action
      - name: Build and push Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.get-tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform.tag-postfix }}:${{ needs.get-tag.outputs.tag }}
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.get-tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform.tag-postfix }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform.tag-postfix }}:${{ needs.get-tag.outputs.tag }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.platform.tag-postfix }}:latest
  create-manifest:
    needs: [ get-tag, build-and-push-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest
        run: |
          docker manifest create ${{ env.IMAGE_NAME }}:${{ needs.get-tag.outputs.tag }} \
            --amend ${{ env.IMAGE_NAME }}-amd:${{ needs.get-tag.outputs.tag }} \
            --amend ${{ env.IMAGE_NAME }}-arm:${{ needs.get-tag.outputs.tag }}
          
          docker manifest create ${{ env.IMAGE_NAME }}:latest \
            --amend ${{ env.IMAGE_NAME }}-amd:latest \
            --amend ${{ env.IMAGE_NAME }}-arm:latest
          
          docker manifest push ${{ env.IMAGE_NAME }}:${{ needs.get-tag.outputs.tag }}
          docker manifest push ${{ env.IMAGE_NAME }}:latest